/**
 * ProcessMaker API
 * This ProcessMaker I/O API provides access to a BPMN 2.0 compliant workflow engine api that is designed to be used as a microservice to support enterprise cloud applications.  The current Alpha 1.0 version supports most of the descriptive class of the BPMN 2.0 specification.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@processmaker.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * TaskConnector_attributes.h
 * 
 * 
 */

#ifndef TaskConnector_attributes_H_
#define TaskConnector_attributes_H_


#include "ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace io {
namespace processmaker {
namespace pmio {
namespace model {

/// <summary>
/// 
/// </summary>
class  TaskConnector_attributes
	: public ModelBase
{
public:
    TaskConnector_attributes();
    virtual ~TaskConnector_attributes();

	/////////////////////////////////////////////
	/// ModelBase overrides
	
    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;
    
 	/////////////////////////////////////////////
	/// TaskConnector_attributes members
	   
    /// <summary>
    /// 
    /// </summary>
    int32_t getTaskId() const;
    void setTaskId(int32_t value);
    bool task_idIsSet() const;
    void unsetTask_id();
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getConnectorClass() const;
    void setConnectorClass(utility::string_t value);
    bool connector_classIsSet() const;
    void unsetConnector_class();
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getInputParameters() const;
    void setInputParameters(utility::string_t value);
    bool input_parametersIsSet() const;
    void unsetInput_parameters();
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getOutputParameters() const;
    void setOutputParameters(utility::string_t value);
    bool output_parametersIsSet() const;
    void unsetOutput_parameters();
    /// <summary>
    /// 
    /// </summary>
    bool getAsyncBefore() const;
    void setAsyncBefore(bool value);
    bool async_beforeIsSet() const;
    void unsetAsync_before();
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getCreatedAt() const;
    void setCreatedAt(utility::string_t value);
    bool created_atIsSet() const;
    void unsetCreated_at();
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getUpdatedAt() const;
    void setUpdatedAt(utility::string_t value);
    bool updated_atIsSet() const;
    void unsetUpdated_at();
    
protected:
    int32_t m_Task_id;
    bool m_Task_idIsSet;
utility::string_t m_Connector_class;
    bool m_Connector_classIsSet;
utility::string_t m_Input_parameters;
    bool m_Input_parametersIsSet;
utility::string_t m_Output_parameters;
    bool m_Output_parametersIsSet;
bool m_Async_before;
    bool m_Async_beforeIsSet;
utility::string_t m_Created_at;
    bool m_Created_atIsSet;
utility::string_t m_Updated_at;
    bool m_Updated_atIsSet;
};

}
}
}
}

#endif /* TaskConnector_attributes_H_ */
